title: Starship Design System
description: A collection of rules allowing for fast and generic spaceship design and play.

repository: ericabxy/starship-design-system

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

collections_dir: docs

collections:
  advanced_systems:
    output: true
  advanced_rules:
    output: true
    permalink: /:title
  basic_rules:
    output: true
    permalink: /:title
  more_rules:
    output: true
    permalink: /:title
  ship_designs:
    output: true
    permalink: /:title
  ship_systems:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'ship_systems'
    values:
      layout: ship-system
